FROM ros:humble-ros-base

WORKDIR /root/ros2_ws

COPY ./bin/install.sh /root/install.sh


# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    libbox2d-dev \
    libeigen3-dev \
    libmatio-dev \
    libgpiod-dev \
    ros-humble-rosbag2-storage-mcap \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/ \
    && echo "export ROS_DOMAIN_ID=123; source /opt/ros/humble/setup.bash; source /root/ros2_ws/install/local_setup.sh" >> /root/.bashrc \
    && /root/install.sh  \
    && /ros_entrypoint.sh


RUN echo aaaa

COPY ./ws/src /root/ros2_ws/src


RUN . /opt/ros/humble/setup.sh && cd /root/ros2_ws && colcon build --symlink-install --packages-select holohover_msgs holohover_drivers holohover_utils holohover_common  holohover_navigation holohover_control holohover_dmpc

COPY ./bin/ocpSpecsSymlink.sh /root/ocpSpecsSymlink.sh
RUN /bin/bash /root/ocpSpecsSymlink.sh amd64


# # # to remove the symlink
# # RUN OCP_SPECS=sProb_chain_QCQP_N10 && \
# #     cd /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS && bash gen_locFuns.sh && \
# #     rm -rf  /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs/$OCP_SPECS && \
# #     cp -r /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs

# # # to remove the symlink
# # RUN OCP_SPECS=sProb_chain_QCQP_N10_100_traj && \
# #     cd /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS && bash gen_locFuns.sh && \
# #     rm -rf  /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs/$OCP_SPECS && \
# #     cp -r /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs

# # to remove the symlink
# RUN OCP_SPECS=sProb_chain_QCQP_N10_2 && \
#     cd /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS && bash gen_locFuns.sh && \
#     rm -rf  /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs/$OCP_SPECS && \
#     cp -r /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs


# # # to remove the symlink
# # RUN OCP_SPECS=sProb_chain_QCQP_N20 && \
# #     cd /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS && bash gen_locFuns.sh && \
# #     rm -rf  /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs/$OCP_SPECS && \
# #     cp -r /root/ros2_ws/src/holohover/holohover_dmpc/ocp_specs/$OCP_SPECS /root/ros2_ws/install/holohover_dmpc/share/holohover_dmpc/ocp_specs