FROM osrf/ros:humble-desktop
#FROM ros:humble

WORKDIR /root/ros2_ws

SHELL ["/bin/bash", "-c"]

COPY ./bin/install.sh /root/install.sh
COPY ./internal/requirements.txt /root/ros2_ws/requirements.txt


# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    libbox2d-dev \
    libeigen3-dev \
    libmatio-dev \
    libgpiod-dev \
    ros-humble-rosbag2-storage-mcap \
    xterm \
    wget \
    gfortran \
    python3-pyqtgraph \
    python3-virtualenv \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log}/


RUN virtualenv -p python3 ./venv \
    && touch ./venv/COLCON_IGNORE \
    && source ./venv/bin/activate \
    && python3 -m pip install -r requirements.txt

RUN echo "source /opt/ros/humble/setup.bash; source /root/ros2_ws/venv/bin/activate; source /root/ros2_ws/install/local_setup.sh" > /root/source.sh \
    && echo "source /root/source.sh" >> /root/.bashrc \
    && /root/install.sh  \
    && /ros_entrypoint.sh \
    && echo "alias build='cd /root/ros2_ws && colcon build --symlink-install' && source install/setup.bash" >> /root/.bashrc \
    && source /root/.bashrc

COPY ./ws/src /root/ros2_ws/src

#RUN . /opt/ros/humble/setup.sh && cd /root/ros2_ws && colcon build --symlink-install 

COPY ./bin/stop_controller.sh /root/stop_controller.sh
COPY ./bin/ocpSpecsSymlink.sh /root/ocpSpecsSymlink.sh
COPY ./bin/fastrtps_profiles_superclient.xml /root/fastrtps_profiles_superclient.xml

RUN /bin/bash /root/ocpSpecsSymlink.sh x86